# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
post_bodies = [
  %Q{Lucas ipsum dolor sit amet antilles zabrak tusken raider hutt c-3p0 tusken raider amidala ackbar hutt luke. Mon maul watto binks. Calamari thrawn moff kessel. Darth c-3po luuke grievous tatooine darth darth obi-wan. Kit solo dooku skywalker yavin jinn darth skywalker. Jawa ben mandalore zabrak. Windu padmé mon jade. Darth lobot grievous anakin qui-gonn mace antilles yoda. Bespin dagobah organa wookiee darth droid obi-wan mothma. Dantooine wampa fett kessel k-3po mandalorians thrawn moff. C-3po obi-wan yavin organa binks darth mon solo.
    Tatooine owen skywalker vader aayla solo. Darth r2-d2 darth moff maul yavin. Darth antilles tusken raider kessel endor. Jinn organa bespin k-3po. Sidious darth calamari watto han dantooine hutt. Greedo ackbar chewbacca moff mandalorians padmé kessel ventress. Lars darth owen organa binks grievous windu. Mustafar greedo dantooine moff. Hutt binks mon jinn binks sidious bothan windu droid. Darth fisto amidala darth moff amidala. Mustafar owen hutt mothma darth. Fisto dagobah calrissian jinn. Ponda hutt fett skywalker zabrak jar qui-gon watto obi-wan.
    Antilles dantooine palpatine solo amidala grievous. Fett mustafar moff amidala jango. Mara utapau ewok calrissian. Wedge jade antilles darth dagobah. Alderaan dantooine kessel skywalker darth antilles. Obi-wan skywalker jango darth organa. Antilles mara kashyyyk darth skywalker yoda greedo organa. Sidious jango mandalore yoda skywalker kessel. Jade chewbacca jawa mon. Hutt mothma alderaan hutt. Padmé hutt moff gamorrean luke hutt jabba kit. Fett ventress mon organa. Coruscant darth jango secura skywalker moff palpatine.},
  %Q{Lucas ipsum dolor sit amet wedge ventress hoth moff antilles moff amidala lobot c-3p0 chewbacca. Hutt sidious endor antilles. Jawa hutt wedge moff skywalker darth skywalker windu lars. Ben leia droid jango vader. Calamari qui-gonn moff sith aayla hutt hutt antilles moff. Skywalker hutt cade darth luke sebulba. Hutt moff ventress sidious wedge bespin hutt anakin darth. Leia han skywalker mon yoda antilles sebulba. Mothma watto organa palpatine obi-wan tatooine binks. K-3po watto mon organa. Coruscant wedge vader tatooine. 
    Calamari dagobah darth antilles antilles. Organa kessel fett darth darth hutt secura bespin. C-3po moff solo cade watto skywalker darth hutt. Anakin lando darth kit jabba obi-wan tatooine solo mandalore. Skywalker palpatine vader chewbacca chewbacca. Padmé solo darth c-3p0 anakin. Sidious hutt darth owen maul boba skywalker padmé darth. Kashyyyk droid solo maul wicket coruscant moff bothan dooku. Antilles kashyyyk antilles ben maul. Moff antilles moff mandalorians. Endor k-3po organa dantooine skywalker luuke moff hutt. 
    Dagobah naboo hutt solo mandalore zabrak. Secura calrissian grievous ahsoka padmé k-3po fett binks. Organa moff endor luke wedge hoth. Windu antilles darth antilles maul darth yoda mothma boba. Dooku organa jinn organa. Organa dantooine tatooine hutt kashyyyk amidala moff kessel. Fisto sidious mandalorians bespin jabba leia antilles ben. Kessel calamari fett wedge binks darth gonk kenobi. Wookiee jawa r2-d2 ackbar jade moff fett leia kashyyyk. Skywalker tatooine mara alderaan. Solo jinn qui-gon hutt mon solo.},
  %Q{Lucas ipsum dolor sit amet boltrunians t'landa selkath watto grievous hobbie owen antemeridian dodonna freedon. Zam jettster kaminoan kitonak kyp derlin lowbacca talz. Mimbanite bardan sing charal. Conan vagaari fode joruus. Coruscant nilgaard moff baba jan moff amanin r4-p17. Onimi -1b letaki antonio moff organa plagueis carondian hobbie. Talz draethos woostoid aramandi dat su. Windu squib dormé gricho yuuzhan -1b. Kit sullustan ponda ulic irek ord utapaun theelin bib. Carondian watto rahm moff desolous. 
    Gorog chazrach frozian umbaran. Kael huk tib sebulba ventress ackbar nar castell dressellian. Medon echani hutt theelin bibble nassau jango. Soontir gank watto ikrit snivvian vagaari priapulin elom. Anzati auril x2 rom massa mod. Iego moff bando glymphid derek cordé spar carondian. Cody frozarns jubnuk gen'dai kenobi. Walon cognus himoran r5-d4. Latter jawa gran zorba bren. Aruzan aurra lyn quermian zhell. Beru yuzzem rodian boba falleen neimoidian. Muzzer calrissian beru firmus jettster tyranus vilim solo kamino. 
    Kaleesh grievous gungan nadon kamino. Mustafar senex r4-p17 winter falleen. Nadon fosh malastare darth piett quadrinaros fel jax bith. Mygeeto kaminoan var breha rancisis sern. Windu dorvalla zhell emtrey. Joelle hutt plagueis firrerreo. Hobbie ulic beru rattatak grodin billaba aurra lando monkey-lizard. Calamari pau'an auril hissa dressellian skywalker kwi. Leia antilles massassi beru anomid gizka kel freedon organa. Sing skywalker calrissian jettster sikan drach'nam. B4-d4 yané droch maul givin.}
]
post_bodies.each_with_index do |body, index|
  Post.create title: "My article #{index}", description: body.split('.').first, body: body, published_at: index.days.ago
end